# Generated by Django 5.2.3 on 2025-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Field', models.CharField(max_length=100)),
                ('Quality', models.CharField(max_length=100)),
                ('Item_ID', models.IntegerField()),
            ],
        ),
    ]
