# Generated by Django 5.2.3 on 2025-07-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Certification', models.CharField(max_length=100)),
            ],
        ),
    ]
