# Generated by Django 5.2.3 on 2025-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
