# Generated by Django 5.2.3 on 2025-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_djangoform'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rollno', models.CharField(max_length=50)),
                ('addrs', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
