# Generated by Django 5.2.3 on 2025-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
