# Generated by Django 5.2.3 on 2025-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='default.jpg', upload_to='static/images')),
            ],
        ),
    ]
