# Generated by Django 5.2.3 on 2025-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_insertimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertimage',
            name='Audio',
            field=models.FileField(default='music.mp3', upload_to='music'),
        ),
        migrations.AlterField(
            model_name='insertimage',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
