# Generated by Django 5.2.3 on 2025-07-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_insertimage_audio_alter_insertimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsertImage',
            new_name='FileFields',
        ),
    ]
