# Generated by Django 5.2.3 on 2025-08-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_insertimage_filefields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
